# Generated by Django 5.2.8 on 2025-11-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(help_text='precio en pesos colombianos', verbose_name='Precio (COP)'),
        ),
    ]
