# Generated by Django 5.2.8 on 2025-11-13 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(help_text='precio en pesos colombianos', validators=[django.core.validators.MinValueValidator(50)], verbose_name='Precio (COP)'),
        ),
    ]
