# Generated by Django 5.2.8 on 2025-11-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
        ('inventario', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='fecha_apertura',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cerrada',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_cierre',
        ),
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='mesero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.mesero'),
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Detalle',
        ),
    ]
