# Generated by Django 5.2.8 on 2025-11-12 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_rename_fecha_apertura_factura_fecha_and_more'),
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mesas.mesa'),
        ),
    ]
