# Generated by Django 5.2.8 on 2025-11-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesero',
            options={'verbose_name_plural': 'Meseros'},
        ),
        migrations.RemoveField(
            model_name='mesero',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mesero',
            name='telefono',
        ),
        migrations.AddField(
            model_name='mesero',
            name='codigo',
            field=models.CharField(default='TEMP', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
