# Generated by Django 5.2.8 on 2025-11-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_alter_mesa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={},
        ),
    ]
